### ISSUE TITLE
merge with master libwacom

### ISSUE THREAD

**Issue by idnovic** [linux-surface/libwacom#2]
I wanted to ask why this is not yet merged with the master libwacom project?

**Comment by qzed** [comment]
This fork is mostly intended for IPTS support. As the IPTS driver is not upstream (and by the looks of it now will not get upstreamed for some time and likely not in the state it currently is), we'll have to keep this separate for now. There's just no point in merging in something unstable.

That's why I closed https://github.com/linuxwacom/libwacom/pull/92 and https://github.com/linuxwacom/libwacom/pull/93 for now.
